---
apiVersion: compositions.io/v1alpha1
kind: InstanceClaim
metadata:
  name: "myapp"
spec:
  parameters:
    region: "us-east-1"
    ami: "ami-06aa3f7caf3a30282"
    instanceType: "t2.small"
    keyName: "repo-final-key"
    Name: "myapp"

  compositionRef:
    name: ec2-instance
